{
  "openapi": "3.1.0",
  "info": {
    "title": "Netflix API",
    "description": "Netflix API",
    "contact": {},
    "version": "1.0"
  },
  "jsonSchemaDialect": "https://json-schema.org/draft/2020-12/schema",
  "servers": [
    {
      "url": "http://localhost:8080",
      "variables": {}
    }
  ],
  "paths": {
    "/new_movies": {
      "post": {
        "tags": [
          "Movie"
        ],
        "summary": "Create movie",
        "operationId": "Createmovie",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/CreatemovieRequest"
                  },
                  {
                    "examples": [
                      {
                        "duration": 120,
                        "title": "The Great Adventure",
                        "ageRating": "SIXTEEN",
                        "contentClassification": "TERROR",
                        "genre": "ACTION",
                        "description": "An epic adventure of a lifetime.",
                        "releaseDate": "2025-01-01"
                      }
                    ]
                  }
                ],
                "contentMediaType": "application/json"
              },
              "example": {
                "duration": 120,
                "title": "The Great Adventure",
                "ageRating": "SIXTEEN",
                "contentClassification": "TERROR",
                "genre": "ACTION",
                "description": "An epic adventure of a lifetime.",
                "releaseDate": "2025-01-01"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "parameters": []
    },
    "/movies/allMovies": {
      "get": {
        "tags": [
          "Movie"
        ],
        "summary": "All Movies XML",
        "description": "Get movies details in XML",
        "operationId": "AllMoviesXML",
        "parameters": [
          {
            "name": "format",
            "in": "query",
            "description": "",
            "required": true,
            "style": "form",
            "explode": true,
            "schema": {
              "type": "string",
              "examples": [
                "xml"
              ]
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "parameters": []
    },
    "/movies/81/details": {
      "get": {
        "tags": [
          "Movie"
        ],
        "summary": "Movie Details with ID",
        "description": "Get movie details with specific movie ID",
        "operationId": "MovieDetailswithID",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "parameters": []
    },
    "/movies/600": {
      "get": {
        "tags": [
          "Movie"
        ],
        "summary": "Fetch data from external API",
        "operationId": "FetchdatafromexternalAPI",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "parameters": []
    },
    "/movies/90": {
      "put": {
        "tags": [
          "Movie"
        ],
        "summary": "Update movie",
        "operationId": "Updatemovie",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/UpdatemovieRequest"
                  },
                  {
                    "examples": [
                      {
                        "duration": 20,
                        "title": "The Great Adventure",
                        "ageRating": "SIXTEEN",
                        "contentClassification": "TERROR",
                        "genre": "ACTION",
                        "description": "An epic adventure of a lifetime.",
                        "releaseDate": "2025-03-01"
                      }
                    ]
                  }
                ],
                "contentMediaType": "application/json"
              },
              "example": {
                "duration": 20,
                "title": "The Great Adventure",
                "ageRating": "SIXTEEN",
                "contentClassification": "TERROR",
                "genre": "ACTION",
                "description": "An epic adventure of a lifetime.",
                "releaseDate": "2025-03-01"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "parameters": []
    },
    "/delete/77": {
      "delete": {
        "tags": [
          "Movie"
        ],
        "summary": "Delete movie",
        "operationId": "Deletemovie",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "parameters": []
    },
    "/netflix/series/create": {
      "post": {
        "tags": [
          "Series"
        ],
        "summary": "Create series",
        "operationId": "Createseries",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/CreateseriesRequest"
                  },
                  {
                    "examples": [
                      {
                        "totalSeasons": 5,
                        "currentSeason": 2,
                        "title": "The Great Adventure"
                      }
                    ]
                  }
                ],
                "contentMediaType": "application/json"
              },
              "example": {
                "totalSeasons": 5,
                "currentSeason": 2,
                "title": "The Great Adventure"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "parameters": []
    },
    "/netflix/series/allSeries": {
      "get": {
        "tags": [
          "Series"
        ],
        "summary": "All Series JSON",
        "operationId": "AllSeriesJSON",
        "parameters": [
          {
            "name": "format",
            "in": "query",
            "description": "",
            "required": true,
            "style": "form",
            "explode": true,
            "schema": {
              "type": "string",
              "examples": [
                "json"
              ]
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "parameters": []
    },
    "/netflix/series/1/details": {
      "get": {
        "tags": [
          "Series"
        ],
        "summary": "Series Details with ID",
        "operationId": "SeriesDetailswithID",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "parameters": []
    },
    "/netflix/series/2/update": {
      "put": {
        "tags": [
          "Series"
        ],
        "summary": "Update series",
        "operationId": "Updateseries",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/UpdateseriesRequest"
                  },
                  {
                    "examples": [
                      {
                        "totalSeasons": 7,
                        "currentSeason": 2,
                        "title": "The Great Adventure"
                      }
                    ]
                  }
                ],
                "contentMediaType": "application/json"
              },
              "example": {
                "totalSeasons": 7,
                "currentSeason": 2,
                "title": "The Great Adventure"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "parameters": []
    },
    "/netflix/series/2/delete": {
      "delete": {
        "tags": [
          "Series"
        ],
        "summary": "Delete series",
        "operationId": "Deleteseries",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "parameters": []
    },
    "/netflix/user/create": {
      "post": {
        "tags": [
          "User"
        ],
        "summary": "Create user",
        "operationId": "Createuser",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/CreateuserRequest"
                  },
                  {
                    "examples": [
                      {
                        "username": "thu",
                        "password": "thutran",
                        "email": "thutran.mon2005@gmail.com"
                      }
                    ]
                  }
                ],
                "contentMediaType": "application/json"
              },
              "example": {
                "username": "thu",
                "password": "thutran",
                "email": "thutran.mon2005@gmail.com"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "parameters": []
    },
    "/netflix/user/activate": {
      "get": {
        "tags": [
          "User"
        ],
        "summary": "Activate account",
        "operationId": "Activateaccount",
        "parameters": [
          {
            "name": "token",
            "in": "query",
            "description": "",
            "required": true,
            "style": "form",
            "explode": true,
            "schema": {
              "type": "string",
              "examples": [
                "1234a"
              ]
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "parameters": []
    },
    "/netflix/user/1": {
      "get": {
        "tags": [
          "User"
        ],
        "summary": "User with ID XML",
        "operationId": "UserwithIDXML",
        "parameters": [
          {
            "name": "format",
            "in": "query",
            "description": "",
            "required": true,
            "style": "form",
            "explode": true,
            "schema": {
              "type": "string",
              "examples": [
                "xml"
              ]
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "parameters": []
    },
    "/netflix/user/10/update": {
      "put": {
        "tags": [
          "User"
        ],
        "summary": "Update user",
        "operationId": "Updateuser",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/UpdateuserRequest"
                  },
                  {
                    "examples": [
                      {
                        "userId": 10,
                        "email": "thutran@gmail.com",
                        "username": "Thu Tran",
                        "accountLockUntil": null,
                        "failedLoginAttempt": 0,
                        "activated": false
                      }
                    ]
                  }
                ],
                "contentMediaType": "application/json"
              },
              "example": {
                "userId": 10,
                "email": "thutran@gmail.com",
                "username": "Thu Tran",
                "accountLockUntil": null,
                "failedLoginAttempt": 0,
                "activated": false
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "parameters": []
    },
    "/netflix/user/9/delete": {
      "delete": {
        "tags": [
          "User"
        ],
        "summary": "Delete user",
        "operationId": "Deleteuser",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "parameters": []
    },
    "/netflix/auth/login": {
      "post": {
        "tags": [
          "Authentication"
        ],
        "summary": "Login",
        "operationId": "Login",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/LoginRequest"
                  },
                  {
                    "examples": [
                      {
                        "email": "thutrann@gmail.com",
                        "password": "thutran"
                      }
                    ]
                  }
                ],
                "contentMediaType": "application/json"
              },
              "example": {
                "email": "thutrann@gmail.com",
                "password": "thutran"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "parameters": []
    },
    "/netflix/auth/forgot-password": {
      "post": {
        "tags": [
          "Authentication"
        ],
        "summary": "Forgot password",
        "description": "Send an email to provide user with token",
        "operationId": "Forgotpassword",
        "parameters": [
          {
            "name": "email",
            "in": "query",
            "description": "",
            "required": true,
            "style": "form",
            "explode": true,
            "schema": {
              "type": "string",
              "examples": [
                "thutran.mon2005@gmail.com"
              ]
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "parameters": []
    },
    "/netflix/auth/reset-password": {
      "post": {
        "tags": [
          "Authentication"
        ],
        "summary": "Reset password",
        "operationId": "Resetpassword",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/ResetpasswordRequest"
                  },
                  {
                    "examples": [
                      {
                        "token": "bc1f9fb8-42dd-4855-bfc7-b3c2083d193f",
                        "newPassword": "thutran1234",
                        "confirmPassword": "thutran1234"
                      }
                    ]
                  }
                ],
                "contentMediaType": "application/json"
              },
              "example": {
                "token": "bc1f9fb8-42dd-4855-bfc7-b3c2083d193f",
                "newPassword": "thutran1234",
                "confirmPassword": "thutran1234"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "parameters": []
    },
    "/netflix/profile/create/1": {
      "post": {
        "tags": [
          "Profile"
        ],
        "summary": "Create profile",
        "operationId": "Createprofile",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/CreateprofileRequest"
                  },
                  {
                    "examples": [
                      {
                        "name": "John Doe",
                        "age": 30,
                        "user": {
                          "userId": 1
                        },
                        "profilePhotoUrl": "profile_photo.jpg",
                        "preferences": [
                          "Action",
                          "Comedy",
                          "Drama"
                        ],
                        "language": "ENGLISH",
                        "watchList": {
                          "items": [
                            "Movie1",
                            "Series1"
                          ]
                        },
                        "viewingHistory": {
                          "recentlyWatched": [
                            "Movie2",
                            "Series2"
                          ],
                          "watchedDates": [
                            "2023-12-01",
                            "2023-12-02"
                          ]
                        }
                      }
                    ]
                  }
                ],
                "contentMediaType": "application/json"
              },
              "example": {
                "name": "John Doe",
                "age": 30,
                "user": {
                  "userId": 1
                },
                "profilePhotoUrl": "profile_photo.jpg",
                "preferences": [
                  "Action",
                  "Comedy",
                  "Drama"
                ],
                "language": "ENGLISH",
                "watchList": {
                  "items": [
                    "Movie1",
                    "Series1"
                  ]
                },
                "viewingHistory": {
                  "recentlyWatched": [
                    "Movie2",
                    "Series2"
                  ],
                  "watchedDates": [
                    "2023-12-01",
                    "2023-12-02"
                  ]
                }
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "parameters": []
    },
    "/netflix/profile/1": {
      "get": {
        "tags": [
          "Profile"
        ],
        "summary": "Profile XML",
        "operationId": "ProfileXML",
        "parameters": [
          {
            "name": "format",
            "in": "query",
            "description": "",
            "required": true,
            "style": "form",
            "explode": true,
            "schema": {
              "type": "string",
              "examples": [
                "xml"
              ]
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "parameters": []
    },
    "/netflix/profile/name/thu": {
      "get": {
        "tags": [
          "Profile"
        ],
        "summary": "Profile name",
        "operationId": "Profilename",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "parameters": []
    },
    "/": {
      "get": {
        "tags": [
          "Profile"
        ],
        "summary": "All profiles of a user",
        "operationId": "Allprofilesofauser",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "parameters": []
    },
    "/netflix/profile/7/update": {
      "put": {
        "tags": [
          "Profile"
        ],
        "summary": "Update profile",
        "operationId": "Updateprofile",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/NewRequestRequest"
                  },
                  {
                    "examples": [
                      {
                        "name": "John Doe",
                        "age": 3,
                        "user": {
                          "userId": 1
                        },
                        "profilePhotoUrl": "hello"
                      }
                    ]
                  }
                ],
                "contentMediaType": "application/json"
              },
              "example": {
                "name": "John Doe",
                "age": 3,
                "user": {
                  "userId": 1
                },
                "profilePhotoUrl": "hello"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "parameters": []
    },
    "/netflix/profile/7/delete": {
      "delete": {
        "tags": [
          "Profile"
        ],
        "summary": "Delete profile",
        "operationId": "Deleteprofile",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "parameters": []
    },
    "/netflix/user/12/subscription/create": {
      "post": {
        "tags": [
          "Subscription"
        ],
        "summary": "Create subscription",
        "operationId": "Createsubscription",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/CreatesubscriptionRequest"
                  },
                  {
                    "examples": [
                      {
                        "tier": "UHD",
                        "startDate": "2025-01-01",
                        "nextBillingDate": "2025-02-01",
                        "isTrialPeriod": true
                      }
                    ]
                  }
                ],
                "contentMediaType": "application/json"
              },
              "example": {
                "tier": "UHD",
                "startDate": "2025-01-01",
                "nextBillingDate": "2025-02-01",
                "isTrialPeriod": true
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "parameters": []
    },
    "/netflix/user/1/subscription": {
      "get": {
        "tags": [
          "Subscription"
        ],
        "summary": "Subscription with userId XML",
        "operationId": "SubscriptionwithuserIdXML",
        "parameters": [
          {
            "name": "format",
            "in": "query",
            "description": "",
            "required": true,
            "style": "form",
            "explode": true,
            "schema": {
              "type": "string",
              "examples": [
                "xml"
              ]
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "parameters": []
    },
    "/netflix/user/12/subscription/3": {
      "get": {
        "tags": [
          "Subscription"
        ],
        "summary": "Subscription",
        "operationId": "Subscription",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "parameters": []
    },
    "/netflix/user/12/subscription/3/update": {
      "put": {
        "tags": [
          "Subscription"
        ],
        "summary": "Update subscription",
        "operationId": "Updatesubscription",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/UpdatesubscriptionRequest"
                  },
                  {
                    "examples": [
                      {
                        "tier": "UHD",
                        "startDate": "2025-01-01",
                        "nextBillingDate": "2025-02-01",
                        "isTrialPeriod": false
                      }
                    ]
                  }
                ],
                "contentMediaType": "application/json"
              },
              "example": {
                "tier": "UHD",
                "startDate": "2025-01-01",
                "nextBillingDate": "2025-02-01",
                "isTrialPeriod": false
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "parameters": []
    },
    "/netflix/user/12/subscription/3/delete": {
      "delete": {
        "tags": [
          "Subscription"
        ],
        "summary": "Delete subscription",
        "operationId": "Deletesubscription",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "parameters": []
    },
    "/netflix/key/generate-key": {
      "post": {
        "tags": [
          "API Key"
        ],
        "summary": "Generate API key",
        "operationId": "GenerateAPIkey",
        "parameters": [
          {
            "name": "userId",
            "in": "query",
            "description": "",
            "required": true,
            "style": "form",
            "explode": true,
            "schema": {
              "type": "integer",
              "contentEncoding": "int32",
              "examples": [
                12
              ]
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "parameters": []
    },
    "/netflix/viewing-history/create/1": {
      "post": {
        "tags": [
          "Viewing History"
        ],
        "summary": "Create viewing history",
        "operationId": "Createviewinghistory",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/CreateviewinghistoryRequest"
                  },
                  {
                    "examples": [
                      {
                        "profile": {
                          "profileId": 1
                        },
                        "movie": {
                          "movieId": 90
                        },
                        "episode": {
                          "episodeId": 1
                        }
                      }
                    ]
                  }
                ],
                "contentMediaType": "application/json"
              },
              "example": {
                "profile": {
                  "profileId": 1
                },
                "movie": {
                  "movieId": 90
                },
                "episode": {
                  "episodeId": 1
                }
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "parameters": []
    },
    "/netflix/viewing-history/profile/10": {
      "get": {
        "tags": [
          "Viewing History"
        ],
        "summary": "Viewing history by profile id",
        "operationId": "Viewinghistorybyprofileid",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "parameters": []
    },
    "/netflix/viewing-history/6": {
      "get": {
        "tags": [
          "Viewing History"
        ],
        "summary": "Viewing history XML",
        "operationId": "ViewinghistoryXML",
        "parameters": [
          {
            "name": "format",
            "in": "query",
            "description": "",
            "required": true,
            "style": "form",
            "explode": true,
            "schema": {
              "type": "string",
              "examples": [
                "xml"
              ]
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "parameters": []
    },
    "/netflix/viewing-history/update/10/history/6": {
      "put": {
        "tags": [
          "Viewing History"
        ],
        "summary": "Update viewing history",
        "operationId": "Updateviewinghistory",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/UpdateviewinghistoryRequest"
                  },
                  {
                    "examples": [
                      {
                        "profileId": 1,
                        "movie": {
                          "movieId": 89
                        },
                        "episode": {
                          "episodeId": 1
                        },
                        "watchedPercentage": 80.0,
                        "viewedAt": "2025-01-19T10:00:00",
                        "stopAt": "2025-01-19T12:00:00"
                      }
                    ]
                  }
                ],
                "contentMediaType": "application/json"
              },
              "example": {
                "profileId": 1,
                "movie": {
                  "movieId": 89
                },
                "episode": {
                  "episodeId": 1
                },
                "watchedPercentage": 80.0,
                "viewedAt": "2025-01-19T10:00:00",
                "stopAt": "2025-01-19T12:00:00"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "parameters": []
    },
    "/netflix/viewing-history/delete/3": {
      "delete": {
        "tags": [
          "Viewing History"
        ],
        "summary": "Delete viewing history",
        "operationId": "Deleteviewinghistory",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "parameters": []
    },
    "/netflix/episodes/create": {
      "post": {
        "tags": [
          "Episode"
        ],
        "summary": "Create episode",
        "operationId": "Createepisode",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/CreateepisodeRequest"
                  },
                  {
                    "examples": [
                      {
                        "episodeName": "Episode 1: The Beginning",
                        "description": "This is the first episode of the series, introducing the main characters and plot.",
                        "duration": 45,
                        "series": {
                          "seriesId": 1
                        }
                      }
                    ]
                  }
                ],
                "contentMediaType": "application/json"
              },
              "example": {
                "episodeName": "Episode 1: The Beginning",
                "description": "This is the first episode of the series, introducing the main characters and plot.",
                "duration": 45,
                "series": {
                  "seriesId": 1
                }
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "parameters": []
    },
    "/netflix/episodes/update/1": {
      "put": {
        "tags": [
          "Episode"
        ],
        "summary": "Update episode",
        "operationId": "Updateepisode",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/UpdateepisodeRequest"
                  },
                  {
                    "examples": [
                      {
                        "episodeName": "Episode 1: The Beginning",
                        "description": "This is the first episode of the series, introducing the main characters and plot.",
                        "duration": 45,
                        "series": {
                          "seriesId": 3
                        }
                      }
                    ]
                  }
                ],
                "contentMediaType": "application/json"
              },
              "example": {
                "episodeName": "Episode 1: The Beginning",
                "description": "This is the first episode of the series, introducing the main characters and plot.",
                "duration": 45,
                "series": {
                  "seriesId": 3
                }
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "parameters": []
    },
    "/netflix/episodes/delete/2": {
      "delete": {
        "tags": [
          "Episode"
        ],
        "summary": "Delete episode",
        "operationId": "Deleteepisode",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "parameters": []
    },
    "/actuator/mappings": {
      "get": {
        "tags": [
          "Misc"
        ],
        "summary": "Mappings",
        "description": "Get all request mappings",
        "operationId": "Mappings",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "parameters": []
    }
  },
  "components": {
    "schemas": {
      "CreatemovieRequest": {
        "title": "CreatemovieRequest",
        "required": [
          "duration",
          "title",
          "ageRating",
          "contentClassification",
          "genre",
          "description",
          "releaseDate"
        ],
        "type": "object",
        "properties": {
          "duration": {
            "type": "integer",
            "contentEncoding": "int32"
          },
          "title": {
            "type": "string"
          },
          "ageRating": {
            "type": "string"
          },
          "contentClassification": {
            "type": "string"
          },
          "genre": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "releaseDate": {
            "type": "string"
          }
        },
        "examples": [
          {
            "duration": 120,
            "title": "The Great Adventure",
            "ageRating": "SIXTEEN",
            "contentClassification": "TERROR",
            "genre": "ACTION",
            "description": "An epic adventure of a lifetime.",
            "releaseDate": "2025-01-01"
          }
        ]
      },
      "UpdatemovieRequest": {
        "title": "UpdatemovieRequest",
        "required": [
          "duration",
          "title",
          "ageRating",
          "contentClassification",
          "genre",
          "description",
          "releaseDate"
        ],
        "type": "object",
        "properties": {
          "duration": {
            "type": "integer",
            "contentEncoding": "int32"
          },
          "title": {
            "type": "string"
          },
          "ageRating": {
            "type": "string"
          },
          "contentClassification": {
            "type": "string"
          },
          "genre": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "releaseDate": {
            "type": "string"
          }
        },
        "examples": [
          {
            "duration": 20,
            "title": "The Great Adventure",
            "ageRating": "SIXTEEN",
            "contentClassification": "TERROR",
            "genre": "ACTION",
            "description": "An epic adventure of a lifetime.",
            "releaseDate": "2025-03-01"
          }
        ]
      },
      "CreateseriesRequest": {
        "title": "CreateseriesRequest",
        "required": [
          "totalSeasons",
          "currentSeason",
          "title"
        ],
        "type": "object",
        "properties": {
          "totalSeasons": {
            "type": "integer",
            "contentEncoding": "int32"
          },
          "currentSeason": {
            "type": "integer",
            "contentEncoding": "int32"
          },
          "title": {
            "type": "string"
          }
        },
        "examples": [
          {
            "totalSeasons": 5,
            "currentSeason": 2,
            "title": "The Great Adventure"
          }
        ]
      },
      "UpdateseriesRequest": {
        "title": "UpdateseriesRequest",
        "required": [
          "totalSeasons",
          "currentSeason",
          "title"
        ],
        "type": "object",
        "properties": {
          "totalSeasons": {
            "type": "integer",
            "contentEncoding": "int32"
          },
          "currentSeason": {
            "type": "integer",
            "contentEncoding": "int32"
          },
          "title": {
            "type": "string"
          }
        },
        "examples": [
          {
            "totalSeasons": 7,
            "currentSeason": 2,
            "title": "The Great Adventure"
          }
        ]
      },
      "CreateuserRequest": {
        "title": "CreateuserRequest",
        "required": [
          "username",
          "password",
          "email"
        ],
        "type": "object",
        "properties": {
          "username": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "email": {
            "type": "string"
          }
        },
        "examples": [
          {
            "username": "thu",
            "password": "thutran",
            "email": "thutran.mon2005@gmail.com"
          }
        ]
      },
      "UpdateuserRequest": {
        "title": "UpdateuserRequest",
        "required": [
          "userId",
          "email",
          "username",
          "accountLockUntil",
          "failedLoginAttempt",
          "activated"
        ],
        "type": "object",
        "properties": {
          "userId": {
            "type": "integer",
            "contentEncoding": "int32"
          },
          "email": {
            "type": "string"
          },
          "username": {
            "type": "string"
          },
          "accountLockUntil": {
            "type": [
              "string",
              "null"
            ]
          },
          "failedLoginAttempt": {
            "type": "integer",
            "contentEncoding": "int32"
          },
          "activated": {
            "type": "boolean"
          }
        },
        "examples": [
          {
            "userId": 10,
            "email": "thutran@gmail.com",
            "username": "Thu Tran",
            "accountLockUntil": null,
            "failedLoginAttempt": 0,
            "activated": false
          }
        ]
      },
      "LoginRequest": {
        "title": "LoginRequest",
        "required": [
          "email",
          "password"
        ],
        "type": "object",
        "properties": {
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        },
        "examples": [
          {
            "email": "thutrann@gmail.com",
            "password": "thutran"
          }
        ]
      },
      "ResetpasswordRequest": {
        "title": "ResetpasswordRequest",
        "required": [
          "token",
          "newPassword",
          "confirmPassword"
        ],
        "type": "object",
        "properties": {
          "token": {
            "type": "string"
          },
          "newPassword": {
            "type": "string"
          },
          "confirmPassword": {
            "type": "string"
          }
        },
        "examples": [
          {
            "token": "bc1f9fb8-42dd-4855-bfc7-b3c2083d193f",
            "newPassword": "thutran1234",
            "confirmPassword": "thutran1234"
          }
        ]
      },
      "CreateprofileRequest": {
        "title": "CreateprofileRequest",
        "required": [
          "name",
          "age",
          "user",
          "profilePhotoUrl",
          "preferences",
          "language",
          "watchList",
          "viewingHistory"
        ],
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "age": {
            "type": "integer",
            "contentEncoding": "int32"
          },
          "user": {
            "$ref": "#/components/schemas/User"
          },
          "profilePhotoUrl": {
            "type": "string"
          },
          "preferences": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": ""
          },
          "language": {
            "type": "string"
          },
          "watchList": {
            "$ref": "#/components/schemas/WatchList"
          },
          "viewingHistory": {
            "$ref": "#/components/schemas/ViewingHistory"
          }
        },
        "examples": [
          {
            "name": "John Doe",
            "age": 30,
            "user": {
              "userId": 1
            },
            "profilePhotoUrl": "profile_photo.jpg",
            "preferences": [
              "Action",
              "Comedy",
              "Drama"
            ],
            "language": "ENGLISH",
            "watchList": {
              "items": [
                "Movie1",
                "Series1"
              ]
            },
            "viewingHistory": {
              "recentlyWatched": [
                "Movie2",
                "Series2"
              ],
              "watchedDates": [
                "2023-12-01",
                "2023-12-02"
              ]
            }
          }
        ]
      },
      "User": {
        "title": "User",
        "required": [
          "userId"
        ],
        "type": "object",
        "properties": {
          "userId": {
            "type": "integer",
            "contentEncoding": "int32"
          }
        },
        "examples": [
          {
            "userId": 1
          }
        ]
      },
      "WatchList": {
        "title": "WatchList",
        "required": [
          "items"
        ],
        "type": "object",
        "properties": {
          "items": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": ""
          }
        },
        "examples": [
          {
            "items": [
              "Movie1",
              "Series1"
            ]
          }
        ]
      },
      "ViewingHistory": {
        "title": "ViewingHistory",
        "required": [
          "recentlyWatched",
          "watchedDates"
        ],
        "type": "object",
        "properties": {
          "recentlyWatched": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": ""
          },
          "watchedDates": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": ""
          }
        },
        "examples": [
          {
            "recentlyWatched": [
              "Movie2",
              "Series2"
            ],
            "watchedDates": [
              "2023-12-01",
              "2023-12-02"
            ]
          }
        ]
      },
      "NewRequestRequest": {
        "title": "NewRequestRequest",
        "required": [
          "name",
          "age",
          "user",
          "profilePhotoUrl"
        ],
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "age": {
            "type": "integer",
            "contentEncoding": "int32"
          },
          "user": {
            "$ref": "#/components/schemas/User"
          },
          "profilePhotoUrl": {
            "type": "string"
          }
        },
        "examples": [
          {
            "name": "John Doe",
            "age": 3,
            "user": {
              "userId": 1
            },
            "profilePhotoUrl": "hello"
          }
        ]
      },
      "CreatesubscriptionRequest": {
        "title": "CreatesubscriptionRequest",
        "required": [
          "tier",
          "startDate",
          "nextBillingDate",
          "isTrialPeriod"
        ],
        "type": "object",
        "properties": {
          "tier": {
            "type": "string"
          },
          "startDate": {
            "type": "string"
          },
          "nextBillingDate": {
            "type": "string"
          },
          "isTrialPeriod": {
            "type": "boolean"
          }
        },
        "examples": [
          {
            "tier": "UHD",
            "startDate": "2025-01-01",
            "nextBillingDate": "2025-02-01",
            "isTrialPeriod": true
          }
        ]
      },
      "UpdatesubscriptionRequest": {
        "title": "UpdatesubscriptionRequest",
        "required": [
          "tier",
          "startDate",
          "nextBillingDate",
          "isTrialPeriod"
        ],
        "type": "object",
        "properties": {
          "tier": {
            "type": "string"
          },
          "startDate": {
            "type": "string"
          },
          "nextBillingDate": {
            "type": "string"
          },
          "isTrialPeriod": {
            "type": "boolean"
          }
        },
        "examples": [
          {
            "tier": "UHD",
            "startDate": "2025-01-01",
            "nextBillingDate": "2025-02-01",
            "isTrialPeriod": false
          }
        ]
      },
      "CreateviewinghistoryRequest": {
        "title": "CreateviewinghistoryRequest",
        "required": [
          "profile",
          "movie",
          "episode"
        ],
        "type": "object",
        "properties": {
          "profile": {
            "$ref": "#/components/schemas/Profile"
          },
          "movie": {
            "$ref": "#/components/schemas/Movie"
          },
          "episode": {
            "$ref": "#/components/schemas/Episode"
          }
        },
        "examples": [
          {
            "profile": {
              "profileId": 1
            },
            "movie": {
              "movieId": 90
            },
            "episode": {
              "episodeId": 1
            }
          }
        ]
      },
      "Profile": {
        "title": "Profile",
        "required": [
          "profileId"
        ],
        "type": "object",
        "properties": {
          "profileId": {
            "type": "integer",
            "contentEncoding": "int32"
          }
        },
        "examples": [
          {
            "profileId": 1
          }
        ]
      },
      "Movie": {
        "title": "Movie",
        "required": [
          "movieId"
        ],
        "type": "object",
        "properties": {
          "movieId": {
            "type": "integer",
            "contentEncoding": "int32"
          }
        },
        "examples": [
          {
            "movieId": 90
          }
        ]
      },
      "Episode": {
        "title": "Episode",
        "required": [
          "episodeId"
        ],
        "type": "object",
        "properties": {
          "episodeId": {
            "type": "integer",
            "contentEncoding": "int32"
          }
        },
        "examples": [
          {
            "episodeId": 1
          }
        ]
      },
      "UpdateviewinghistoryRequest": {
        "title": "UpdateviewinghistoryRequest",
        "required": [
          "profileId",
          "movie",
          "episode",
          "watchedPercentage",
          "viewedAt",
          "stopAt"
        ],
        "type": "object",
        "properties": {
          "profileId": {
            "type": "integer",
            "contentEncoding": "int32"
          },
          "movie": {
            "$ref": "#/components/schemas/Movie"
          },
          "episode": {
            "$ref": "#/components/schemas/Episode"
          },
          "watchedPercentage": {
            "type": "number"
          },
          "viewedAt": {
            "type": "string"
          },
          "stopAt": {
            "type": "string"
          }
        },
        "examples": [
          {
            "profileId": 1,
            "movie": {
              "movieId": 89
            },
            "episode": {
              "episodeId": 1
            },
            "watchedPercentage": 80.0,
            "viewedAt": "2025-01-19T10:00:00",
            "stopAt": "2025-01-19T12:00:00"
          }
        ]
      },
      "CreateepisodeRequest": {
        "title": "CreateepisodeRequest",
        "required": [
          "episodeName",
          "description",
          "duration",
          "series"
        ],
        "type": "object",
        "properties": {
          "episodeName": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "duration": {
            "type": "integer",
            "contentEncoding": "int32"
          },
          "series": {
            "$ref": "#/components/schemas/Series"
          }
        },
        "examples": [
          {
            "episodeName": "Episode 1: The Beginning",
            "description": "This is the first episode of the series, introducing the main characters and plot.",
            "duration": 45,
            "series": {
              "seriesId": 1
            }
          }
        ]
      },
      "Series": {
        "title": "Series",
        "required": [
          "seriesId"
        ],
        "type": "object",
        "properties": {
          "seriesId": {
            "type": "integer",
            "contentEncoding": "int32"
          }
        },
        "examples": [
          {
            "seriesId": 1
          }
        ]
      },
      "UpdateepisodeRequest": {
        "title": "UpdateepisodeRequest",
        "required": [
          "episodeName",
          "description",
          "duration",
          "series"
        ],
        "type": "object",
        "properties": {
          "episodeName": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "duration": {
            "type": "integer",
            "contentEncoding": "int32"
          },
          "series": {
            "$ref": "#/components/schemas/Series"
          }
        },
        "examples": [
          {
            "episodeName": "Episode 1: The Beginning",
            "description": "This is the first episode of the series, introducing the main characters and plot.",
            "duration": 45,
            "series": {
              "seriesId": 3
            }
          }
        ]
      }
    }
  },
  "tags": [
    {
      "name": "Movie",
      "description": "Movie requests"
    },
    {
      "name": "Series",
      "description": "Series request"
    },
    {
      "name": "User",
      "description": "User requests"
    },
    {
      "name": "Authentication",
      "description": "Auhentication requests"
    },
    {
      "name": "Profile",
      "description": "Profile requests"
    },
    {
      "name": "Subscription",
      "description": "Subscription requests"
    },
    {
      "name": "API Key",
      "description": "Generate and validate API key"
    },
    {
      "name": "Viewing History",
      "description": "Viewing history requests"
    },
    {
      "name": "Episode",
      "description": "Episode requests"
    },
    {
      "name": "Misc",
      "description": ""
    }
  ]
}